-- Criação da tabela de logs de status
CREATE TABLE IF NOT EXISTS chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES chats(conversation_id) ON DELETE CASCADE,
    status_anterior TEXT,
    status_novo TEXT NOT NULL,
    alterado_por TEXT, -- Email ou ID do usuário que fez a ação
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Segurança)
ALTER TABLE chat_logs ENABLE ROW LEVEL SECURITY;

-- Política de leitura (todos autenticados podem ver logs)
CREATE POLICY "Permitir leitura de logs" ON chat_logs FOR SELECT USING (true);

-- Política de inserção (backend autenticado pode inserir)
CREATE POLICY "Permitir inserção de logs" ON chat_logs FOR INSERT WITH CHECK (true);


-- (Opcional) Trigger para gerar log automaticamente quando o status mudar na tabela chats
-- Isso garante que mesmo se alterar pelo painel do Supabase, o log é gerado.

CREATE OR REPLACE FUNCTION log_chat_status_change()
RETURNS TRIGGER AS $$
BEGIN
    IF (OLD.status IS DISTINCT FROM NEW.status) THEN
        INSERT INTO chat_logs (conversation_id, status_anterior, status_novo, alterado_por)
        VALUES (NEW.conversation_id, OLD.status, NEW.status, 'sistema_trigger');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_log_chat_status
AFTER UPDATE ON chats
FOR EACH ROW
EXECUTE FUNCTION log_chat_status_change();
